# Generated by Django 5.0.7 on 2024-08-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0003_product_remove_job_customer_remove_deposit_job_and_more'),
    ]

    operations = [
    ]
