# Generated by Django 5.0.7 on 2024-08-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0004_auto_20240805_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
