# Generated by Django 5.0.7 on 2024-08-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0006_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_couriers', 'Can manage couriers'), ('can_manage_storekeepers', 'Can manage storekeepers'), ('can_manage_clients', 'Can manage clients'), ('can_view_overall_info', 'Can view overall information'), ('can_manage_articles', 'Can manage articles'), ('can_notify_courier', 'Can notify courier'), ('can_manage_refunds', 'Can manage refunds'), ('can_view_deliveries', 'Can view deliveries'), ('can_manage_deliveries', 'Can manage deliveries'), ('can_make_orders', 'Can make orders'), ('can_get_articles_delivered', 'Can get articles delivered'), ('can_decline_orders', 'Can decline orders'), ('can_view_cart', 'Can view cart'), ('can_add_to_cart', 'Can add to cart')]},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS.product')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMS.order')),
            ],
        ),
    ]
