# Generated by Django 5.0.7 on 2024-08-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0013_alter_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
    ]
