# Generated by Django 5.0.7 on 2024-08-09 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0017_producttype_article_receiver_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='destination_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='pickup_address',
            field=models.CharField(max_length=255),
        ),
    ]
