# Generated by Django 5.0.7 on 2024-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0020_remove_article_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(to='DMS.product'),
        ),
    ]
