# Generated by Django 5.0.7 on 2024-08-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0022_notification_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='receiver_name',
        ),
        migrations.AddField(
            model_name='article',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='destination_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='pickup_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(related_name='articles', to='DMS.product'),
        ),
        migrations.AlterField(
            model_name='article',
            name='receiver_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='sender_phone',
            field=models.CharField(max_length=20),
        ),
    ]
