# Generated by Django 5.0.7 on 2024-08-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0023_remove_article_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='total_price',
        ),
    ]
