# Generated by Django 5.0.7 on 2024-08-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0025_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='article',
            name='destination_address',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='article',
            name='receiver_quarter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_quarter', to='DMS.adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='receiver_town',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_town', to='DMS.adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='sender_quarter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender_quarter', to='DMS.adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='sender_town',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender_town', to='DMS.adresse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(blank=True, to='DMS.product'),
        ),
        migrations.AlterField(
            model_name='article',
            name='receiver_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='sender_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='weight',
            field=models.FloatField(),
        ),
    ]
