# Generated by Django 5.0.7 on 2024-08-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0026_remove_article_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
