# Generated by Django 5.0.7 on 2024-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0027_article_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
